<?php
defined( 'ABSPATH' ) || exit;

return array(
    'default_texts' => [
            'banner_title_text'             => __( "Cookies Consent", "alternative-site-settings" ),
            'banner_text'                   => __( "This site uses cookies to ensure proper operation and analytics. You can refuse or accept cookies. Your choice does not affect cookies required for site operation and authorization. You can read all the rules for processing cookies and other personal data by clicking on the links below.", "alternative-site-settings" ),
            'customize_title_text'          => __( "Cookie customize", "alternative-site-settings" ),
            'customize_intro_text'          => __( "Customize your cookies as you wish! Select the ones you want, except for technical (required) cookies: without them, the site won&#039;t work. We&#039;ll remember your choice and ask you to update it later.", "alternative-site-settings" ),
            'accept_all_btn_txt'            => __( "Accept All", "alternative-site-settings" ),
            'accept_selected_btn_txt'       => __( "Accept Selected", "alternative-site-settings" ),
            'customize_btn_txt'             => __( "Customize", "alternative-site-settings" ),
            'back_btn_txt'                  => __( "Back", "alternative-site-settings" ),
            'decline_btn_txt'               => __( "Reject All", "alternative-site-settings" ),
            'tech_ctg_note_text'            => __( "These cookies are essential for our website to function properly. They enable basic functionality, site authorization, navigation, and access to secure areas.", "alternative-site-settings" ),
            'functional_ctg_note_text'      => __( "These cookies enhance security and remember your website settings. They are not stored on our servers or shared with third parties.", "alternative-site-settings" ),
            'analytics_ctg_note_text'       => __( "These cookies collect statistics needed to understand which services, products, and sections you like most. This helps make the website more user-friendly and functional.", "alternative-site-settings" ),
            'marketing_ctg_note_text'       => __( "These cookies are used to track visitors across the site in order to display relevant and engaging advertising.", "alternative-site-settings" ),
            'other_ctg_note_text'           => __( "Other cookies", "alternative-site-settings" ),
    ],

    'default_values' => [
            'banner_position'                   => 'bottom-full',
            'banner_width'                      => 600,
            'banner_v_padding'                  => 24,
            'banner_h_padding'                  => 24,
            'banner_border_radius'              => 24,
            'banner_bgcolor'                    => '#ebebeb',
            'banner_title_color'                => '#444',
            'banner_txt_color'                  => '#444',
            'customize_title_color'             => '#444',
            'customize_txt_color'               => '#444',
            'btn_border_width'                  => 2,
            'btn_border_radius'                 => 6,
            'default_btn_bgcolor'               => '#dbdbdb',
            'default_btn_hov_bgcolor'           => '#d5d5d5',
            'default_btn_txt_color'             => '#444',
            'default_btn_hov_txt_color'         => '#333',
            'default_btn_border_color'          => '#7b7b7b',
            'default_btn_hov_border_color'      => '#535353',
            'active_switch_color'               => '#78a2c5',
            'active_switch_border_color'        => '#6c86a1',
            'banner_delay_time'                 => 1,
            'cookie_consent_days'               => 14,
    ],

    'button_settings_labels' => [
        'accept_all_btn' => [
            'text'              => __( 'Text on the Accept button', 'alternative-site-settings' ),
            'bgcolor'           => __( 'Accept button background color', 'alternative-site-settings' ),
            'hov_bgcolor'       => __( 'Accept button background color on hover', 'alternative-site-settings' ),
            'txt_color'         => __( 'Accept button text color', 'alternative-site-settings' ),
            'hov_txt_color'     => __( 'Accept button text color on hover', 'alternative-site-settings' ),
            'border_color'      => __( 'Accept button border color', 'alternative-site-settings' ),
            'hov_border_color'  => __( 'Accept button border color on hover', 'alternative-site-settings' ),
        ],
        'accept_selected_btn' => [
            'text'              => __( 'Text on the Accept Selected button', 'alternative-site-settings' ),
            'bgcolor'           => __( 'Background color of the Accept Selected button', 'alternative-site-settings' ),
            'hov_bgcolor'       => __( 'Background color of the Accept Selected button on hover', 'alternative-site-settings' ),
            'txt_color'         => __( 'Text color of the Accept Selected button', 'alternative-site-settings' ),
            'hov_txt_color'     => __( 'Text color of the Accept Selected button on hover', 'alternative-site-settings' ),
            'border_color'      => __( 'Border color of the Accept Selected button', 'alternative-site-settings' ),
            'hov_border_color'  => __( 'Border color of the Accept Selected button on hover', 'alternative-site-settings' ),
        ],
        'customize_btn' => [
            'text'              => __( 'Text on the Customize button', 'alternative-site-settings' ),
            'bgcolor'           => __( 'Customize button background color', 'alternative-site-settings' ),
            'hov_bgcolor'       => __( 'Customize button background color on hover', 'alternative-site-settings' ),
            'txt_color'         => __( 'Customize button text color', 'alternative-site-settings' ),
            'hov_txt_color'     => __( 'Customize button text color on hover', 'alternative-site-settings' ),
            'border_color'      => __( 'Customize button border color', 'alternative-site-settings' ),
            'hov_border_color'  => __( 'Customize button border color on hover', 'alternative-site-settings' ),
        ],
        'decline_btn' => [
            'text'              => __( 'Text on the Decline button', 'alternative-site-settings' ),
            'bgcolor'           => __( 'Decline button background color', 'alternative-site-settings' ),
            'hov_bgcolor'       => __( 'Decline button background color on hover', 'alternative-site-settings' ),
            'txt_color'         => __( 'Decline button text color', 'alternative-site-settings' ),
            'hov_txt_color'     => __( 'Decline button text color on hover', 'alternative-site-settings' ),
            'border_color'      => __( 'Decline button border color', 'alternative-site-settings' ),
            'hov_border_color'  => __( 'Decline button border color on hover', 'alternative-site-settings' ),
        ],
        'back_btn' => [
            'text'              => __( 'Text on the Back button', 'alternative-site-settings' ),
            'bgcolor'           => __( 'Back button background color', 'alternative-site-settings' ),
            'hov_bgcolor'       => __( 'Back button background color on hover', 'alternative-site-settings' ),
            'txt_color'         => __( 'Back button text color', 'alternative-site-settings' ),
            'hov_txt_color'     => __( 'Back button text color on hover', 'alternative-site-settings' ),
            'border_color'      => __( 'Back button border color', 'alternative-site-settings' ),
            'hov_border_color'  => __( 'Back button border color on hover', 'alternative-site-settings' ),
        ],
    ],
        
    'banner_position_list' => [
            'top-full'      => __( "top full-width", "alternative-site-settings" ),
            'bottom-full'   => __( "bottom full-width", "alternative-site-settings" ),
            'top-left'      => __( "top left", "alternative-site-settings" ),
            'top-center'    => __( "top center", "alternative-site-settings" ),
            'top-right'     => __( "top right", "alternative-site-settings" ),
            'middle-left'   => __( "middle left", "alternative-site-settings" ),
            'center'        => __( "center", "alternative-site-settings" ),
            'middle-right'  => __( "middle right", "alternative-site-settings" ),
            'bottom-left'   => __( "bottom left", "alternative-site-settings" ),
            'bottom-center' => __( "bottom center", "alternative-site-settings" ),
            'bottom-right'  => __( "bottom right", "alternative-site-settings" )
    ],

    'cookie_select_list' => [
            'tech'          => __( "Technical (essential) cookies", "alternative-site-settings" ),
            'functional'    => __( "Functional cookies", "alternative-site-settings" ),
            'analytics'     => __( "Analytical cookies", "alternative-site-settings" ),
            'marketing'     => __( "Marketing cookies", "alternative-site-settings" ),
            'other'         => __( "Other cookies", "alternative-site-settings" ),
    ],

    'wordpress_cookie_prefs' => [
            'wordpress_logged_in_',
            'wordpress_sec_',
            'wordpress_test_cookie',
            'wp-settings-',
            'wp-postpass_',
            'comment_author_',
            'wp-settings-time-'
    ],
);
